from django.urls import path

from .views import scholars_views, students_views, profile_views, auth_views, activities_views, research_interests_views, admins_views, Invite, hdc, admin

app_name = "mba_admin"
urlpatterns = [
    path("", activities_views.index, name="index"),
    path("signin", auth_views.signin, name="signin"),
    path("signout", auth_views.signout, name="signout"),
    path("scholars", scholars_views.scholars, name="scholars"),
    path("supervisors", scholars_views.supervisors, name="supervisors"),
    path("examiners", scholars_views.examiners, name="examiners"),
    path("manage/student/<int:id>",  students_views.manage_student, name="manage_student"),
    path("onboard/scholar", scholars_views.onboard_scholar, name="onboard_scholar"),
    path("onboard/scholars", scholars_views.onboard_supervisor_bulk, name="onboard_scholars"),
    path("onboard/examiners", scholars_views.onboard_examiners_bulk, name="onboard_examiners"),
    path("onboard/students", students_views.student_bulk_onboard, name="onboard_students"),
    path("invite/superivosr", Invite.send_invite, name="send_invite"),
    path("appoint/supervisor", Invite.appoint_supervisor, name="appoint_sup"),
    path("researchInterest", research_interests_views.researchInterest, name="research_interest"),
    path("researchInterest/add", research_interests_views.add_research_interest, name="add_research_interest"),
    path("researchInterest/update", research_interests_views.update_research_interest, name="update_research_interest"),
    path("students", students_views.students, name="students"),
    path("manage/admins", admins_views.manage_admins, name="manage_admins"),
    path("profile", profile_views.profile, name="profile"),
    path("hdc", hdc.hdc,name="hdc" ),
    path("titles/submitted", hdc.titles_submissions,name="titles_submitted" ),
    path("intent/submitted", hdc.intent_submissions,name="intent_submitted" ),
    path("hdc/intent/submitted", hdc.hdc_intent_submissions,name="hdc_intent_submission" ),
    path("intent/decline", admins_views.decline_intent,name="decline_intent" ),
    path("hdc/download/cv", hdc.download_cv,name="download_cv" ),
    path("hdc/decline/intent", hdc.decline_intent,name="hdc_decline_intent"),
    path("hdc/approve/intent", hdc.approve_intent,name="hdc_approve_intent"),
    path("hdc/approved", hdc.approved_hdc,name="approved_hdc" ),
    path("nominations", hdc.nominations_submitted,name="nomination_submitted" ),
    path('approve/title', admins_views.approve_title, name='approve_title'),
    path('decline/title', admins_views.decline_title, name='decline_title'),
    path('hdc/approve/title', hdc.approve_title, name='hdc_approve_title'),
    path('hdc/decline/title', hdc.decline_title, name='hdc_decline_title'),
    path('approve/notice/form', admins_views.approve_notice_form, name='approve_notice_form'),
    path('decline/notice/form', admins_views.decline_notice_form, name='decline_notice_form'),
    path("hdc/accept_hdc", hdc.hdc_approve,name="accept_hdc" ),
    path("hdc/reject", hdc.hdc_reject,name="reject_hdc" ),
    path("hdc/appoint/assessor", scholars_views.appoint_assessor,name="appoint_assessor" ),
    path("hdc/update/assessor", scholars_views.update_assessor,name="update_assessor" ),
    path("hdc/submission/nominations", hdc.hdc_nomination_submission,name="hdc_nominations" ),
    path("hdc/submissions/titles", hdc.hdc_titles_submission,name="hdc_titles_submission" ),
    path("hdc/approve/assessor", hdc.approve_assessor,name="approve_assessor" ),
    path("hdc/decline/assessor", hdc.decline_assessor,name="decline_assessor" ),
    path("hdc/add/coment", hdc.hdc_add_comment,name="hdc_add_comment" ),
    path("hdc/return/project", hdc.send_project_to_admin,name="send_project_to_admin" ),
    path("return/project", hdc.send_project_to_supervisor,name="send_project_to_supervisor" ),
    path("send/assessor/invite", Invite.send_assessor_invite,name="send_assessor_invite" ),
    path('activate/student/<int:user_id>', admins_views.activate_student, name='activate_student'),
    path('deactivate/student/<int:user_id>', admins_views.suspend_student, name='suspend_student'),
    path('activate/examiner/<int:user_id>', admins_views.activate_examiner,name=
         'activate_examiner'),
    path('deactivate/examiner/<int:user_id>', admins_views.suspend_examiner, name="suspend_examiner"),
    path('activate/supervisor/<int:user_id>', admins_views.activate_supervisor,name=
         'activate_supervisor'),
    path('deactivate/supervisor/<int:user_id>', admins_views.suspend_supervisor, name="suspend_supervisor"),
    path("reset/project/<int:project_id>", students_views.reset_project, name="reset_project"),
    path("upload/project<int:project_id>", admins_views.upload_project, name="upload_project"),
    path('create/user', admin.create_user_view, name='create_user')
 
]

