CREATE TABLE IF NOT EXISTS public.auth_group
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_group_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_name_key UNIQUE (name)
)


CREATE TABLE IF NOT EXISTS public.auth_group_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    group_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id),
    CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id)
        REFERENCES public.auth_permission (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id)
        REFERENCES public.auth_group (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
)


CREATE TABLE IF NOT EXISTS public.auth_permission
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_permission_pkey PRIMARY KEY (id),
    CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename),
    CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id)
        REFERENCES public.django_content_type (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
)


CREATE TABLE IF NOT EXISTS public.django_admin_log
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    action_time timestamp with time zone NOT NULL,
    object_id text COLLATE pg_catalog."default",
    object_repr character varying(200) COLLATE pg_catalog."default" NOT NULL,
    action_flag smallint NOT NULL,
    change_message text COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_pkey PRIMARY KEY (id),
    CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id)
        REFERENCES public.django_content_type (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT django_admin_log_user_id_c564eba6_fk_mbamain_auser_id FOREIGN KEY (user_id)
        REFERENCES public.mbamain_auser (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT django_admin_log_action_flag_check CHECK (action_flag >= 0)
)




CREATE TABLE IF NOT EXISTS public.django_content_type
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    app_label character varying(100) COLLATE pg_catalog."default" NOT NULL,
    model character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT django_content_type_pkey PRIMARY KEY (id),
    CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model)
)



CREATE TABLE IF NOT EXISTS public.django_migrations
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    app character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    applied timestamp with time zone NOT NULL,
    CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
)



CREATE TABLE IF NOT EXISTS public.django_session
(
    session_key character varying(40) COLLATE pg_catalog."default" NOT NULL,
    session_data text COLLATE pg_catalog."default" NOT NULL,
    expire_date timestamp with time zone NOT NULL,
    CONSTRAINT django_session_pkey PRIMARY KEY (session_key)
)



CREATE TABLE IF NOT EXISTS public.mbamain_auser
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    password character varying(128) COLLATE pg_catalog."default" NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    email character varying(254) COLLATE pg_catalog."default" NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    user_type integer NOT NULL,
    role_type integer,
    has_profile boolean NOT NULL,
    has_signature boolean NOT NULL,
    has_cv boolean NOT NULL,
    CONSTRAINT mbamain_auser_pkey PRIMARY KEY (id),
    CONSTRAINT mbamain_auser_username_key UNIQUE (username)
)



CREATE TABLE IF NOT EXISTS public.mbamain_auser_groups
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    auser_id bigint NOT NULL,
    group_id integer NOT NULL,
    CONSTRAINT mbamain_auser_groups_pkey PRIMARY KEY (id),
    CONSTRAINT mbamain_auser_groups_auser_id_group_id_1759aade_uniq UNIQUE (auser_id, group_id),
    CONSTRAINT mbamain_auser_groups_auser_id_6b8292c4_fk_mbamain_auser_id FOREIGN KEY (auser_id)
        REFERENCES public.mbamain_auser (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT mbamain_auser_groups_group_id_e15c8209_fk_auth_group_id FOREIGN KEY (group_id)
        REFERENCES public.auth_group (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
)


CREATE TABLE IF NOT EXISTS public.mbamain_auser_user_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    auser_id bigint NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT mbamain_auser_user_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT mbamain_auser_user_permi_auser_id_permission_id_001e556a_uniq UNIQUE (auser_id, permission_id),
    CONSTRAINT mbamain_auser_user_p_auser_id_ee6c5ec3_fk_mbamain_a FOREIGN KEY (auser_id)
        REFERENCES public.mbamain_auser (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT mbamain_auser_user_p_permission_id_dfef9b6c_fk_auth_perm FOREIGN KEY (permission_id)
        REFERENCES public.auth_permission (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
)


CREATE TABLE IF NOT EXISTS public.mbamain_cv
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    cv_file character varying(100) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL,
    name character varying(255) COLLATE pg_catalog."default",
    user_id bigint NOT NULL,
    CONSTRAINT mbamain_cv_pkey PRIMARY KEY (id),
    CONSTRAINT mbamain_cv_user_id_key UNIQUE (user_id),
    CONSTRAINT mbamain_cv_user_id_dd7b1a07_fk_mbamain_auser_id FOREIGN KEY (user_id)
        REFERENCES public.mbamain_auser (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
)



CREATE TABLE IF NOT EXISTS public.mbamain_examminerprofile
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name text COLLATE pg_catalog."default",
    surname text COLLATE pg_catalog."default",
    title text COLLATE pg_catalog."default",
    qualification text COLLATE pg_catalog."default",
    affiliation text COLLATE pg_catalog."default",
    street_address text COLLATE pg_catalog."default",
    cell_phone text COLLATE pg_catalog."default",
    skills text COLLATE pg_catalog."default",
    email character varying(254) COLLATE pg_catalog."default",
    number_of_students_supervised integer NOT NULL,
    current_affiliation text COLLATE pg_catalog."default",
    number_publications integer NOT NULL,
    approved_before boolean NOT NULL,
    international_assessor boolean NOT NULL,
    academic_experience bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT mbamain_examminerprofile_pkey PRIMARY KEY (id),
    CONSTRAINT mbamain_examminerprofile_user_id_key UNIQUE (user_id),
    CONSTRAINT mbamain_examminerprofile_user_id_ae2d2ebc_fk_mbamain_auser_id FOREIGN KEY (user_id)
        REFERENCES public.mbamain_auser (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT mbamain_examminerprofile_number_of_students_supervised_check CHECK (number_of_students_supervised >= 0),
    CONSTRAINT mbamain_examminerprofile_number_publications_check CHECK (number_publications >= 0),
    CONSTRAINT mbamain_examminerprofile_academic_experience_check CHECK (academic_experience >= 0)
)



CREATE TABLE IF NOT EXISTS public.mbamain_invite
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    invite_type boolean NOT NULL,
    read boolean,
    response boolean,
    responeded_date date,
    created_at timestamp with time zone NOT NULL,
    count integer NOT NULL,
    user_id bigint NOT NULL,
    project_id bigint,
    CONSTRAINT mbamain_invite_pkey PRIMARY KEY (id),
    CONSTRAINT mbamain_invite_project_id_b0c654c8_fk_mbamain_project_id FOREIGN KEY (project_id)
        REFERENCES public.mbamain_project (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT mbamain_invite_user_id_b8af2e47_fk_mbamain_auser_id FOREIGN KEY (user_id)
        REFERENCES public.mbamain_auser (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
)


CREATE TABLE IF NOT EXISTS public.mbamain_invitescheduler
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    last_sent_date timestamp with time zone,
    created boolean,
    CONSTRAINT mbamain_invitescheduler_pkey PRIMARY KEY (id)
)


CREATE TABLE IF NOT EXISTS public.mbamain_jbs5
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    initials character varying COLLATE pg_catalog."default",
    superivosr_signed boolean,
    date_signed_student date NOT NULL,
    supervisors_signed_date date NOT NULL,
    study_type text COLLATE pg_catalog."default",
    ir text COLLATE pg_catalog."default",
    qualification text COLLATE pg_catalog."default",
    title text COLLATE pg_catalog."default",
    research_specific boolean,
    secondary_focus boolean,
    registration_date date,
    co_supervisor_surname text COLLATE pg_catalog."default",
    co_supervisor_initials text COLLATE pg_catalog."default",
    co_supervisor_department text COLLATE pg_catalog."default",
    student_signed boolean NOT NULL,
    supervisor_signed boolean NOT NULL,
    proposed_supervisor text COLLATE pg_catalog."default",
    proposed_co_supervisor text COLLATE pg_catalog."default",
    previously_approved_supervisor text COLLATE pg_catalog."default",
    amended_supervisor text COLLATE pg_catalog."default",
    previously_approved_co_supervisor text COLLATE pg_catalog."default",
    amended_co_supervisor text COLLATE pg_catalog."default",
    previous_title text COLLATE pg_catalog."default",
    proposed_amendment_title text COLLATE pg_catalog."default",
    project_id bigint NOT NULL,
    student_signature_id bigint,
    CONSTRAINT mbamain_jbs5_pkey PRIMARY KEY (id),
    CONSTRAINT mbamain_jbs5_project_id_key UNIQUE (project_id),
    CONSTRAINT mbamain_jbs5_project_id_ad16b3e9_fk_mbamain_project_id FOREIGN KEY (project_id)
        REFERENCES public.mbamain_project (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT mbamain_jbs5_student_signature_id_e08be2f4_fk_mbamain_s FOREIGN KEY (student_signature_id)
        REFERENCES public.mbamain_signature (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
)





CREATE TABLE IF NOT EXISTS public.mbamain_jbs10
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_uj_staff boolean,
    ethical_clearance_number text COLLATE pg_catalog."default",
    capstone_project text COLLATE pg_catalog."default",
    proposed_title text COLLATE pg_catalog."default",
    is_4ir_research boolean,
    previous_title text COLLATE pg_catalog."default",
    supervisor_name text COLLATE pg_catalog."default",
    supervisor_staff_number text COLLATE pg_catalog."default",
    cosupervisor1_name text COLLATE pg_catalog."default",
    cosupervisor1_staff_number text COLLATE pg_catalog."default",
    cosupervisor2_name text COLLATE pg_catalog."default",
    cosupervisor2_staff_number text COLLATE pg_catalog."default",
    previous_supervisor_name text COLLATE pg_catalog."default",
    previous_supervisor_staff_number text COLLATE pg_catalog."default",
    previous_cosupervisor_name text COLLATE pg_catalog."default",
    previous_cosupervisor_stuff_number text COLLATE pg_catalog."default",
    internal_assessor text COLLATE pg_catalog."default",
    external_assessor1_name text COLLATE pg_catalog."default",
    external_assessor1_staff_number text COLLATE pg_catalog."default",
    external_assessor1_affiliation text COLLATE pg_catalog."default",
    external_assessor1_qualification text COLLATE pg_catalog."default",
    external_assessor1_email character varying(254) COLLATE pg_catalog."default",
    external_assessor2_name text COLLATE pg_catalog."default",
    external_assessor2_staff_number text COLLATE pg_catalog."default",
    external_assessor2_affiliation text COLLATE pg_catalog."default",
    external_assessor2_qualification text COLLATE pg_catalog."default",
    external_assessor2_email character varying(254) COLLATE pg_catalog."default",
    external_assessor3_name text COLLATE pg_catalog."default",
    external_assessor3_staff_number text COLLATE pg_catalog."default",
    external_assessor3_affiliation text COLLATE pg_catalog."default",
    external_assessor3_qualification text COLLATE pg_catalog."default",
    external_assessor3_email character varying(254) COLLATE pg_catalog."default",
    previous_assessor_name text COLLATE pg_catalog."default",
    previous_assessor_qualification text COLLATE pg_catalog."default",
    previous_assessor_staff_number text COLLATE pg_catalog."default",
    previous_external_assessor1_name text COLLATE pg_catalog."default",
    previous_external_assessor1_staff_number text COLLATE pg_catalog."default",
    previous_external_assessor1_affiliation text COLLATE pg_catalog."default",
    previous_external_assessor1_qualification text COLLATE pg_catalog."default",
    previous_external_assessor1_email character varying(254) COLLATE pg_catalog."default",
    previous_external_assessor2_name text COLLATE pg_catalog."default",
    previous_external_assessor2_staff_number text COLLATE pg_catalog."default",
    previous_external_assessor2_affiliation text COLLATE pg_catalog."default",
    previous_external_assessor2_qualification text COLLATE pg_catalog."default",
    previous_external_assessor2_email character varying(254) COLLATE pg_catalog."default",
    previous_external_assessor3_name text COLLATE pg_catalog."default",
    previous_external_assessor3_staff_number text COLLATE pg_catalog."default",
    previous_external_assessor3_affiliation text COLLATE pg_catalog."default",
    previous_external_assessor3_qualification text COLLATE pg_catalog."default",
    previous_external_assessor3_email character varying(254) COLLATE pg_catalog."default",
    supervisor_signed text COLLATE pg_catalog."default",
    supervisor_signed_date date,
    student_signed text COLLATE pg_catalog."default",
    student_signed_date date,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    project_id bigint NOT NULL,
    CONSTRAINT mbamain_jbs10_pkey PRIMARY KEY (id),
    CONSTRAINT mbamain_jbs10_project_id_key UNIQUE (project_id),
    CONSTRAINT mbamain_jbs10_project_id_e914a0cf_fk_mbamain_project_id FOREIGN KEY (project_id)
        REFERENCES public.mbamain_project (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
)



CREATE TABLE IF NOT EXISTS public.mbamain_nominationform
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    co_supervisor_full_names text COLLATE pg_catalog."default",
    co_supervisor_department text COLLATE pg_catalog."default",
    co_supervisor_phone text COLLATE pg_catalog."default",
    co_supervisor_email text COLLATE pg_catalog."default",
    degree text COLLATE pg_catalog."default",
    qualification text COLLATE pg_catalog."default",
    supervisor_signed boolean,
    supervisor_sign_date date,
    project_id bigint NOT NULL,
    CONSTRAINT mbamain_nominationform_pkey PRIMARY KEY (id),
    CONSTRAINT mbamain_nominationform_project_id_key UNIQUE (project_id),
    CONSTRAINT mbamain_nominationfo_project_id_f651f7c7_fk_mbamain_p FOREIGN KEY (project_id)
        REFERENCES public.mbamain_project (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
)


CREATE TABLE IF NOT EXISTS public.mbamain_noticetosubmitform
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    date_signed_student date NOT NULL,
    auth_student character varying(100) COLLATE pg_catalog."default",
    supervisors_comment text COLLATE pg_catalog."default",
    supervisor_agree boolean,
    supervisors_signed_date date NOT NULL,
    approved_hdc boolean,
    title_approved_hdc boolean,
    ethicals text COLLATE pg_catalog."default",
    nominated_examinners boolean,
    co_supervisor_details text COLLATE pg_catalog."default",
    student_signed boolean NOT NULL,
    supervisor_signed boolean NOT NULL,
    project_id bigint NOT NULL,
    dos_signature_id bigint,
    hod_signature_id bigint,
    primary_supervisor_signature_id bigint,
    secondary_supervisor_signature_id bigint,
    student_signature_id bigint,
    CONSTRAINT mbamain_noticetosubmitform_pkey PRIMARY KEY (id),
    CONSTRAINT mbamain_noticetosubmitform_project_id_key UNIQUE (project_id),
    CONSTRAINT mbamain_noticetosubm_dos_signature_id_7f9a11e9_fk_mbamain_s FOREIGN KEY (dos_signature_id)
        REFERENCES public.mbamain_signature (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT mbamain_noticetosubm_hod_signature_id_c0a0ee24_fk_mbamain_s FOREIGN KEY (hod_signature_id)
        REFERENCES public.mbamain_signature (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT mbamain_noticetosubm_primary_supervisor_s_aa6e1e30_fk_mbamain_s FOREIGN KEY (primary_supervisor_signature_id)
        REFERENCES public.mbamain_signature (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT mbamain_noticetosubm_project_id_7f7ac261_fk_mbamain_p FOREIGN KEY (project_id)
        REFERENCES public.mbamain_project (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT mbamain_noticetosubm_secondary_supervisor_29656fc5_fk_mbamain_s FOREIGN KEY (secondary_supervisor_signature_id)
        REFERENCES public.mbamain_signature (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT mbamain_noticetosubm_student_signature_id_47724584_fk_mbamain_s FOREIGN KEY (student_signature_id)
        REFERENCES public.mbamain_signature (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
)



CREATE TABLE IF NOT EXISTS public.mbamain_passwordresettoken
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    token character varying(8) COLLATE pg_catalog."default" NOT NULL,
    created_date timestamp with time zone NOT NULL,
    max_time integer NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT mbamain_passwordresettoken_pkey PRIMARY KEY (id),
    CONSTRAINT mbamain_passwordresettoken_user_id_key UNIQUE (user_id),
    CONSTRAINT mbamain_passwordresettoken_user_id_e863672b_fk_mbamain_auser_id FOREIGN KEY (user_id)
        REFERENCES public.mbamain_auser (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
)


CREATE TABLE IF NOT EXISTS public.mbamain_project
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    project_title character varying(200) COLLATE pg_catalog."default" NOT NULL,
    project_description text COLLATE pg_catalog."default" NOT NULL,
    project_start_date date NOT NULL,
    created_date timestamp with time zone NOT NULL,
    ehical_clearance_number integer,
    qualification character varying(100) COLLATE pg_catalog."default",
    project_status integer NOT NULL,
    title_approved boolean,
    nomination_form_approved boolean,
    nomination_form_submitted boolean,
    nomination_form_hdc_verified boolean,
    intent_form_approved boolean,
    intent_form_submitted boolean,
    intent_form_hdc_verified boolean,
    sdg_goal text COLLATE pg_catalog."default",
    assessor_1_name text COLLATE pg_catalog."default",
    assessor_1_email text COLLATE pg_catalog."default",
    assessor_1_surname text COLLATE pg_catalog."default",
    assessor_1_email_sent boolean,
    assessor_2_name text COLLATE pg_catalog."default",
    assessor_2_email text COLLATE pg_catalog."default",
    assessor_2_surname text COLLATE pg_catalog."default",
    assessor_2_email_sent boolean,
    primary_supervisor integer,
    comments text COLLATE pg_catalog."default",
    hdc_comments text COLLATE pg_catalog."default",
    assessor_1_appointed boolean,
    assessor_2_appointed boolean,
    assessor_1_responded boolean,
    assessor_2_responded boolean,
    assessor_3_responded boolean,
    assessor_1_response boolean,
    assessor_1_invite_sent boolean,
    assessor_2_response boolean,
    assessor_2_invite_sent boolean,
    assessor_3_response boolean,
    assessor_3_invite_sent boolean,
    assessor_1_approved boolean,
    assessor_2_approved boolean,
    assessor_3_approved boolean,
    discipline text COLLATE pg_catalog."default" NOT NULL,
    assessor_1 integer,
    assessor_2 integer,
    assessor_3 integer,
    student_id bigint NOT NULL,
    CONSTRAINT mbamain_project_pkey PRIMARY KEY (id),
    CONSTRAINT mbamain_project_student_id_c98e2974_fk_mbamain_auser_id FOREIGN KEY (student_id)
        REFERENCES public.mbamain_auser (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
)


CREATE TABLE IF NOT EXISTS public.mbamain_researchinterest
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    created_by text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT mbamain_researchinterest_pkey PRIMARY KEY (id),
    CONSTRAINT mbamain_researchinterest_name_key UNIQUE (name)
)



CREATE TABLE IF NOT EXISTS public.mbamain_signature
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    img_path character varying(100) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT mbamain_signature_pkey PRIMARY KEY (id),
    CONSTRAINT mbamain_signature_user_id_key UNIQUE (user_id),
    CONSTRAINT mbamain_signature_user_id_9898f271_fk_mbamain_auser_id FOREIGN KEY (user_id)
        REFERENCES public.mbamain_auser (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
)


CREATE TABLE IF NOT EXISTS public.mbamain_studentprofile
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name text COLLATE pg_catalog."default",
    surname text COLLATE pg_catalog."default",
    title text COLLATE pg_catalog."default",
    contact text COLLATE pg_catalog."default",
    student_no text COLLATE pg_catalog."default",
    secondary_email character varying(254) COLLATE pg_catalog."default",
    module text COLLATE pg_catalog."default",
    block_id text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL,
    degree text COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default",
    user_id bigint NOT NULL,
    CONSTRAINT mbamain_studentprofile_pkey PRIMARY KEY (id),
    CONSTRAINT mbamain_studentprofile_user_id_key UNIQUE (user_id),
    CONSTRAINT mbamain_studentprofile_user_id_f8675222_fk_mbamain_auser_id FOREIGN KEY (user_id)
        REFERENCES public.mbamain_auser (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
)


CREATE TABLE IF NOT EXISTS public.mbamain_studentsupervisorform
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    initials_student character varying(100) COLLATE pg_catalog."default",
    initials_supervisor character varying(100) COLLATE pg_catalog."default",
    date_signed_student date NOT NULL,
    supervisors_signed_date date NOT NULL,
    student_address text COLLATE pg_catalog."default",
    supervisor_department text COLLATE pg_catalog."default",
    co_supervisor_department text COLLATE pg_catalog."default",
    co_supervisor_full_names text COLLATE pg_catalog."default",
    co_supervisor_initials text COLLATE pg_catalog."default",
    co_supervisor_surname text COLLATE pg_catalog."default",
    student_signed boolean NOT NULL,
    supervisor_signed boolean NOT NULL,
    project_id bigint NOT NULL,
    CONSTRAINT mbamain_studentsupervisorform_pkey PRIMARY KEY (id),
    CONSTRAINT mbamain_studentsupervisorform_project_id_key UNIQUE (project_id),
    CONSTRAINT mbamain_studentsuper_project_id_7690e705_fk_mbamain_p FOREIGN KEY (project_id)
        REFERENCES public.mbamain_project (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
)


CREATE TABLE IF NOT EXISTS public.mbamain_supervisorprofile
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name text COLLATE pg_catalog."default",
    surname text COLLATE pg_catalog."default",
    title text COLLATE pg_catalog."default",
    skills text COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default",
    department text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL,
    "position" text COLLATE pg_catalog."default",
    contact text COLLATE pg_catalog."default",
    students integer,
    user_id bigint NOT NULL,
    CONSTRAINT mbamain_supervisorprofile_pkey PRIMARY KEY (id),
    CONSTRAINT mbamain_supervisorprofile_user_id_key UNIQUE (user_id),
    CONSTRAINT mbamain_supervisorprofile_user_id_961c19d5_fk_mbamain_auser_id FOREIGN KEY (user_id)
        REFERENCES public.mbamain_auser (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
)