--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: mbamain_auser; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mbamain_auser (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    user_type integer NOT NULL,
    role_type integer,
    has_profile boolean NOT NULL,
    has_signature boolean NOT NULL,
    has_cv boolean NOT NULL
);


ALTER TABLE public.mbamain_auser OWNER TO postgres;

--
-- Name: mbamain_auser_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mbamain_auser_groups (
    id bigint NOT NULL,
    auser_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.mbamain_auser_groups OWNER TO postgres;

--
-- Name: mbamain_auser_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mbamain_auser_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mbamain_auser_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mbamain_auser_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mbamain_auser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mbamain_auser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mbamain_auser_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mbamain_auser_user_permissions (
    id bigint NOT NULL,
    auser_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.mbamain_auser_user_permissions OWNER TO postgres;

--
-- Name: mbamain_auser_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mbamain_auser_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mbamain_auser_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mbamain_cv; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mbamain_cv (
    id bigint NOT NULL,
    cv_file character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    name character varying(255),
    user_id bigint NOT NULL
);


ALTER TABLE public.mbamain_cv OWNER TO postgres;

--
-- Name: mbamain_cv_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mbamain_cv ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mbamain_cv_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mbamain_examminerprofile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mbamain_examminerprofile (
    id bigint NOT NULL,
    name text,
    surname text,
    title text,
    qualification text,
    affiliation text,
    street_address text,
    cell_phone text,
    skills text,
    email character varying(254),
    number_of_students_supervised integer NOT NULL,
    current_affiliation text,
    number_publications integer NOT NULL,
    international_assessor boolean NOT NULL,
    academic_experience bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    approved_before boolean NOT NULL,
    CONSTRAINT mbamain_examminerprofile_academic_experience_check CHECK ((academic_experience >= 0)),
    CONSTRAINT mbamain_examminerprofile_number_of_students_supervised_check CHECK ((number_of_students_supervised >= 0)),
    CONSTRAINT mbamain_examminerprofile_number_publications_check CHECK ((number_publications >= 0))
);


ALTER TABLE public.mbamain_examminerprofile OWNER TO postgres;

--
-- Name: mbamain_examminerprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mbamain_examminerprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mbamain_examminerprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mbamain_invite; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mbamain_invite (
    id bigint NOT NULL,
    read boolean,
    response boolean,
    responeded_date date,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    project_id bigint,
    count integer NOT NULL,
    invite_type boolean NOT NULL
);


ALTER TABLE public.mbamain_invite OWNER TO postgres;

--
-- Name: mbamain_invite_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mbamain_invite ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mbamain_invite_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mbamain_invitescheduler; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mbamain_invitescheduler (
    id bigint NOT NULL,
    last_sent_date timestamp with time zone,
    created boolean
);


ALTER TABLE public.mbamain_invitescheduler OWNER TO postgres;

--
-- Name: mbamain_invitescheduler_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mbamain_invitescheduler ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mbamain_invitescheduler_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mbamain_jbs10; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mbamain_jbs10 (
    id bigint NOT NULL,
    is_uj_staff boolean,
    ethical_clearance_number text,
    capstone_project text,
    proposed_title text,
    is_4ir_research boolean,
    previous_title text,
    supervisor_name text,
    supervisor_staff_number text,
    cosupervisor1_name text,
    cosupervisor1_staff_number text,
    cosupervisor2_name text,
    cosupervisor2_staff_number text,
    internal_assessor text,
    external_assessor1_name text,
    external_assessor1_affiliation text,
    external_assessor1_qualification text,
    external_assessor1_email character varying(254),
    external_assessor2_name text,
    external_assessor2_affiliation text,
    external_assessor2_qualification text,
    external_assessor2_email character varying(254),
    external_assessor3_name text,
    external_assessor3_affiliation text,
    external_assessor3_qualification text,
    external_assessor3_email character varying(254),
    supervisor_signed text,
    supervisor_signed_date date,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    project_id bigint NOT NULL,
    student_signed text,
    student_signed_date date,
    external_assessor1_staff_number text,
    external_assessor2_staff_number text,
    external_assessor3_staff_number text,
    previous_assessor_name text,
    previous_assessor_staff_number text,
    previous_cosupervisor_name text,
    previous_cosupervisor_stuff_number text,
    previous_external_assessor1_affiliation text,
    previous_external_assessor1_email character varying(254),
    previous_external_assessor1_name text,
    previous_external_assessor1_qualification text,
    previous_external_assessor1_staff_number text,
    previous_external_assessor2_affiliation text,
    previous_external_assessor2_email character varying(254),
    previous_external_assessor2_name text,
    previous_external_assessor2_qualification text,
    previous_external_assessor2_staff_number text,
    previous_external_assessor3_affiliation text,
    previous_external_assessor3_email character varying(254),
    previous_external_assessor3_name text,
    previous_external_assessor3_qualification text,
    previous_external_assessor3_staff_number text,
    previous_supervisor_name text,
    previous_supervisor_staff_number text,
    previous_assessor_qualification text
);


ALTER TABLE public.mbamain_jbs10 OWNER TO postgres;

--
-- Name: mbamain_jbs10_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mbamain_jbs10 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mbamain_jbs10_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mbamain_jbs5; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mbamain_jbs5 (
    id bigint NOT NULL,
    initials character varying,
    superivosr_signed boolean,
    date_signed_student date NOT NULL,
    supervisors_signed_date date NOT NULL,
    study_type text,
    ir text,
    qualification text,
    title text,
    research_specific boolean,
    secondary_focus boolean,
    registration_date date,
    co_supervisor_surname text,
    co_supervisor_initials text,
    co_supervisor_department text,
    student_signed boolean NOT NULL,
    supervisor_signed boolean NOT NULL,
    project_id bigint NOT NULL,
    student_signature_id bigint,
    amended_co_supervisor text,
    amended_supervisor text,
    previous_title text,
    previously_approved_co_supervisor text,
    previously_approved_supervisor text,
    proposed_amendment_title text,
    proposed_co_supervisor text,
    proposed_supervisor text
);


ALTER TABLE public.mbamain_jbs5 OWNER TO postgres;

--
-- Name: mbamain_jbs5_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mbamain_jbs5 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mbamain_jbs5_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mbamain_nominationform; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mbamain_nominationform (
    id bigint NOT NULL,
    co_supervisor_full_names text,
    co_supervisor_department text,
    co_supervisor_phone text,
    co_supervisor_email text,
    supervisor_signed boolean,
    supervisor_sign_date date,
    project_id bigint NOT NULL,
    degree text,
    qualification text
);


ALTER TABLE public.mbamain_nominationform OWNER TO postgres;

--
-- Name: mbamain_nominationform_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mbamain_nominationform ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mbamain_nominationform_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mbamain_noticetosubmitform; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mbamain_noticetosubmitform (
    id bigint NOT NULL,
    date_signed_student date NOT NULL,
    auth_student character varying(100),
    supervisors_comment text,
    supervisor_agree boolean,
    supervisors_signed_date date NOT NULL,
    approved_hdc boolean,
    title_approved_hdc boolean,
    ethicals text,
    nominated_examinners boolean,
    co_supervisor_details text,
    student_signed boolean NOT NULL,
    supervisor_signed boolean NOT NULL,
    project_id bigint NOT NULL,
    dos_signature_id bigint,
    hod_signature_id bigint,
    primary_supervisor_signature_id bigint,
    secondary_supervisor_signature_id bigint,
    student_signature_id bigint
);


ALTER TABLE public.mbamain_noticetosubmitform OWNER TO postgres;

--
-- Name: mbamain_noticetosubmitform_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mbamain_noticetosubmitform ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mbamain_noticetosubmitform_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mbamain_passwordresettoken; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mbamain_passwordresettoken (
    id bigint NOT NULL,
    token character varying(8) NOT NULL,
    created_date timestamp with time zone NOT NULL,
    max_time integer NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.mbamain_passwordresettoken OWNER TO postgres;

--
-- Name: mbamain_passwordresettoken_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mbamain_passwordresettoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mbamain_passwordresettoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mbamain_project; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mbamain_project (
    id bigint NOT NULL,
    project_title character varying(200) NOT NULL,
    project_description text NOT NULL,
    project_start_date date NOT NULL,
    created_date timestamp with time zone NOT NULL,
    ehical_clearance_number integer,
    qualification character varying(100),
    project_status integer NOT NULL,
    primary_supervisor integer,
    discipline text NOT NULL,
    assessor_1 integer,
    assessor_2 integer,
    assessor_3 integer,
    student_id bigint NOT NULL,
    assessor_1_appointed boolean,
    assessor_2_appointed boolean,
    comments text,
    sdg_goal text,
    assessor_1_approved boolean,
    assessor_2_approved boolean,
    assessor_3_approved boolean,
    hdc_comments text,
    assessor_1_email text,
    assessor_1_name text,
    assessor_1_surname text,
    assessor_2_email text,
    assessor_2_name text,
    assessor_2_surname text,
    title_approved boolean,
    nomination_form_approved boolean,
    nomination_form_submitted boolean,
    nomination_form_hdc_verified boolean,
    intent_form_approved boolean,
    intent_form_hdc_verified boolean,
    intent_form_submitted boolean,
    assessor_1_invite_sent boolean,
    assessor_1_responded boolean,
    assessor_1_response boolean,
    assessor_2_invite_sent boolean,
    assessor_2_responded boolean,
    assessor_2_response boolean,
    assessor_3_invite_sent boolean,
    assessor_3_responded boolean,
    assessor_3_response boolean,
    assessor_1_email_sent boolean,
    assessor_2_email_sent boolean
);


ALTER TABLE public.mbamain_project OWNER TO postgres;

--
-- Name: mbamain_project_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mbamain_project ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mbamain_project_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mbamain_researchinterest; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mbamain_researchinterest (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    created_by text,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.mbamain_researchinterest OWNER TO postgres;

--
-- Name: mbamain_researchinterest_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mbamain_researchinterest ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mbamain_researchinterest_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mbamain_signature; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mbamain_signature (
    id bigint NOT NULL,
    img_path character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.mbamain_signature OWNER TO postgres;

--
-- Name: mbamain_signature_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mbamain_signature ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mbamain_signature_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mbamain_studentprofile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mbamain_studentprofile (
    id bigint NOT NULL,
    name text,
    surname text,
    title text,
    contact text,
    student_no text,
    secondary_email character varying(254),
    module text,
    block_id text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    degree text,
    address text,
    user_id bigint NOT NULL
);


ALTER TABLE public.mbamain_studentprofile OWNER TO postgres;

--
-- Name: mbamain_studentprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mbamain_studentprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mbamain_studentprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mbamain_studentsupervisorform; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mbamain_studentsupervisorform (
    id bigint NOT NULL,
    initials_student character varying(100),
    initials_supervisor character varying(100),
    date_signed_student date NOT NULL,
    supervisors_signed_date date NOT NULL,
    student_address text,
    supervisor_department text,
    co_supervisor_department text,
    co_supervisor_full_names text,
    co_supervisor_initials text,
    co_supervisor_surname text,
    student_signed boolean NOT NULL,
    supervisor_signed boolean NOT NULL,
    project_id bigint NOT NULL
);


ALTER TABLE public.mbamain_studentsupervisorform OWNER TO postgres;

--
-- Name: mbamain_studentsupervisorform_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mbamain_studentsupervisorform ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mbamain_studentsupervisorform_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mbamain_supervisorprofile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mbamain_supervisorprofile (
    id bigint NOT NULL,
    name text,
    surname text,
    title text,
    skills text,
    created_at timestamp with time zone NOT NULL,
    "position" text,
    contact text,
    students integer,
    user_id bigint NOT NULL,
    address text,
    department text
);


ALTER TABLE public.mbamain_supervisorprofile OWNER TO postgres;

--
-- Name: mbamain_supervisorprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mbamain_supervisorprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mbamain_supervisorprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: mbamain_auser_groups mbamain_auser_groups_auser_id_group_id_1759aade_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_auser_groups
    ADD CONSTRAINT mbamain_auser_groups_auser_id_group_id_1759aade_uniq UNIQUE (auser_id, group_id);


--
-- Name: mbamain_auser_groups mbamain_auser_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_auser_groups
    ADD CONSTRAINT mbamain_auser_groups_pkey PRIMARY KEY (id);


--
-- Name: mbamain_auser mbamain_auser_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_auser
    ADD CONSTRAINT mbamain_auser_pkey PRIMARY KEY (id);


--
-- Name: mbamain_auser_user_permissions mbamain_auser_user_permi_auser_id_permission_id_001e556a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_auser_user_permissions
    ADD CONSTRAINT mbamain_auser_user_permi_auser_id_permission_id_001e556a_uniq UNIQUE (auser_id, permission_id);


--
-- Name: mbamain_auser_user_permissions mbamain_auser_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_auser_user_permissions
    ADD CONSTRAINT mbamain_auser_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: mbamain_auser mbamain_auser_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_auser
    ADD CONSTRAINT mbamain_auser_username_key UNIQUE (username);


--
-- Name: mbamain_cv mbamain_cv_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_cv
    ADD CONSTRAINT mbamain_cv_pkey PRIMARY KEY (id);


--
-- Name: mbamain_cv mbamain_cv_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_cv
    ADD CONSTRAINT mbamain_cv_user_id_key UNIQUE (user_id);


--
-- Name: mbamain_examminerprofile mbamain_examminerprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_examminerprofile
    ADD CONSTRAINT mbamain_examminerprofile_pkey PRIMARY KEY (id);


--
-- Name: mbamain_examminerprofile mbamain_examminerprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_examminerprofile
    ADD CONSTRAINT mbamain_examminerprofile_user_id_key UNIQUE (user_id);


--
-- Name: mbamain_invite mbamain_invite_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_invite
    ADD CONSTRAINT mbamain_invite_pkey PRIMARY KEY (id);


--
-- Name: mbamain_invitescheduler mbamain_invitescheduler_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_invitescheduler
    ADD CONSTRAINT mbamain_invitescheduler_pkey PRIMARY KEY (id);


--
-- Name: mbamain_jbs10 mbamain_jbs10_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_jbs10
    ADD CONSTRAINT mbamain_jbs10_pkey PRIMARY KEY (id);


--
-- Name: mbamain_jbs10 mbamain_jbs10_project_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_jbs10
    ADD CONSTRAINT mbamain_jbs10_project_id_key UNIQUE (project_id);


--
-- Name: mbamain_jbs5 mbamain_jbs5_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_jbs5
    ADD CONSTRAINT mbamain_jbs5_pkey PRIMARY KEY (id);


--
-- Name: mbamain_jbs5 mbamain_jbs5_project_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_jbs5
    ADD CONSTRAINT mbamain_jbs5_project_id_key UNIQUE (project_id);


--
-- Name: mbamain_nominationform mbamain_nominationform_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_nominationform
    ADD CONSTRAINT mbamain_nominationform_pkey PRIMARY KEY (id);


--
-- Name: mbamain_nominationform mbamain_nominationform_project_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_nominationform
    ADD CONSTRAINT mbamain_nominationform_project_id_key UNIQUE (project_id);


--
-- Name: mbamain_noticetosubmitform mbamain_noticetosubmitform_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_noticetosubmitform
    ADD CONSTRAINT mbamain_noticetosubmitform_pkey PRIMARY KEY (id);


--
-- Name: mbamain_noticetosubmitform mbamain_noticetosubmitform_project_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_noticetosubmitform
    ADD CONSTRAINT mbamain_noticetosubmitform_project_id_key UNIQUE (project_id);


--
-- Name: mbamain_passwordresettoken mbamain_passwordresettoken_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_passwordresettoken
    ADD CONSTRAINT mbamain_passwordresettoken_pkey PRIMARY KEY (id);


--
-- Name: mbamain_passwordresettoken mbamain_passwordresettoken_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_passwordresettoken
    ADD CONSTRAINT mbamain_passwordresettoken_user_id_key UNIQUE (user_id);


--
-- Name: mbamain_project mbamain_project_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_project
    ADD CONSTRAINT mbamain_project_pkey PRIMARY KEY (id);


--
-- Name: mbamain_researchinterest mbamain_researchinterest_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_researchinterest
    ADD CONSTRAINT mbamain_researchinterest_name_key UNIQUE (name);


--
-- Name: mbamain_researchinterest mbamain_researchinterest_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_researchinterest
    ADD CONSTRAINT mbamain_researchinterest_pkey PRIMARY KEY (id);


--
-- Name: mbamain_signature mbamain_signature_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_signature
    ADD CONSTRAINT mbamain_signature_pkey PRIMARY KEY (id);


--
-- Name: mbamain_signature mbamain_signature_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_signature
    ADD CONSTRAINT mbamain_signature_user_id_key UNIQUE (user_id);


--
-- Name: mbamain_studentprofile mbamain_studentprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_studentprofile
    ADD CONSTRAINT mbamain_studentprofile_pkey PRIMARY KEY (id);


--
-- Name: mbamain_studentprofile mbamain_studentprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_studentprofile
    ADD CONSTRAINT mbamain_studentprofile_user_id_key UNIQUE (user_id);


--
-- Name: mbamain_studentsupervisorform mbamain_studentsupervisorform_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_studentsupervisorform
    ADD CONSTRAINT mbamain_studentsupervisorform_pkey PRIMARY KEY (id);


--
-- Name: mbamain_studentsupervisorform mbamain_studentsupervisorform_project_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_studentsupervisorform
    ADD CONSTRAINT mbamain_studentsupervisorform_project_id_key UNIQUE (project_id);


--
-- Name: mbamain_supervisorprofile mbamain_supervisorprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_supervisorprofile
    ADD CONSTRAINT mbamain_supervisorprofile_pkey PRIMARY KEY (id);


--
-- Name: mbamain_supervisorprofile mbamain_supervisorprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_supervisorprofile
    ADD CONSTRAINT mbamain_supervisorprofile_user_id_key UNIQUE (user_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: mbamain_auser_groups_auser_id_6b8292c4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX mbamain_auser_groups_auser_id_6b8292c4 ON public.mbamain_auser_groups USING btree (auser_id);


--
-- Name: mbamain_auser_groups_group_id_e15c8209; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX mbamain_auser_groups_group_id_e15c8209 ON public.mbamain_auser_groups USING btree (group_id);


--
-- Name: mbamain_auser_user_permissions_auser_id_ee6c5ec3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX mbamain_auser_user_permissions_auser_id_ee6c5ec3 ON public.mbamain_auser_user_permissions USING btree (auser_id);


--
-- Name: mbamain_auser_user_permissions_permission_id_dfef9b6c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX mbamain_auser_user_permissions_permission_id_dfef9b6c ON public.mbamain_auser_user_permissions USING btree (permission_id);


--
-- Name: mbamain_auser_username_c04e8624_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX mbamain_auser_username_c04e8624_like ON public.mbamain_auser USING btree (username varchar_pattern_ops);


--
-- Name: mbamain_invite_project_id_b0c654c8; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX mbamain_invite_project_id_b0c654c8 ON public.mbamain_invite USING btree (project_id);


--
-- Name: mbamain_invite_user_id_b8af2e47; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX mbamain_invite_user_id_b8af2e47 ON public.mbamain_invite USING btree (user_id);


--
-- Name: mbamain_jbs5_student_signature_id_e08be2f4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX mbamain_jbs5_student_signature_id_e08be2f4 ON public.mbamain_jbs5 USING btree (student_signature_id);


--
-- Name: mbamain_noticetosubmitform_dos_signature_id_7f9a11e9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX mbamain_noticetosubmitform_dos_signature_id_7f9a11e9 ON public.mbamain_noticetosubmitform USING btree (dos_signature_id);


--
-- Name: mbamain_noticetosubmitform_hod_signature_id_c0a0ee24; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX mbamain_noticetosubmitform_hod_signature_id_c0a0ee24 ON public.mbamain_noticetosubmitform USING btree (hod_signature_id);


--
-- Name: mbamain_noticetosubmitform_primary_supervisor_signatu_aa6e1e30; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX mbamain_noticetosubmitform_primary_supervisor_signatu_aa6e1e30 ON public.mbamain_noticetosubmitform USING btree (primary_supervisor_signature_id);


--
-- Name: mbamain_noticetosubmitform_secondary_supervisor_signa_29656fc5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX mbamain_noticetosubmitform_secondary_supervisor_signa_29656fc5 ON public.mbamain_noticetosubmitform USING btree (secondary_supervisor_signature_id);


--
-- Name: mbamain_noticetosubmitform_student_signature_id_47724584; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX mbamain_noticetosubmitform_student_signature_id_47724584 ON public.mbamain_noticetosubmitform USING btree (student_signature_id);


--
-- Name: mbamain_project_student_id_c98e2974; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX mbamain_project_student_id_c98e2974 ON public.mbamain_project USING btree (student_id);


--
-- Name: mbamain_researchinterest_name_a8110242_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX mbamain_researchinterest_name_a8110242_like ON public.mbamain_researchinterest USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_mbamain_auser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_mbamain_auser_id FOREIGN KEY (user_id) REFERENCES public.mbamain_auser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mbamain_auser_groups mbamain_auser_groups_auser_id_6b8292c4_fk_mbamain_auser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_auser_groups
    ADD CONSTRAINT mbamain_auser_groups_auser_id_6b8292c4_fk_mbamain_auser_id FOREIGN KEY (auser_id) REFERENCES public.mbamain_auser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mbamain_auser_groups mbamain_auser_groups_group_id_e15c8209_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_auser_groups
    ADD CONSTRAINT mbamain_auser_groups_group_id_e15c8209_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mbamain_auser_user_permissions mbamain_auser_user_p_auser_id_ee6c5ec3_fk_mbamain_a; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_auser_user_permissions
    ADD CONSTRAINT mbamain_auser_user_p_auser_id_ee6c5ec3_fk_mbamain_a FOREIGN KEY (auser_id) REFERENCES public.mbamain_auser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mbamain_auser_user_permissions mbamain_auser_user_p_permission_id_dfef9b6c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_auser_user_permissions
    ADD CONSTRAINT mbamain_auser_user_p_permission_id_dfef9b6c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mbamain_cv mbamain_cv_user_id_dd7b1a07_fk_mbamain_auser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_cv
    ADD CONSTRAINT mbamain_cv_user_id_dd7b1a07_fk_mbamain_auser_id FOREIGN KEY (user_id) REFERENCES public.mbamain_auser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mbamain_examminerprofile mbamain_examminerprofile_user_id_ae2d2ebc_fk_mbamain_auser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_examminerprofile
    ADD CONSTRAINT mbamain_examminerprofile_user_id_ae2d2ebc_fk_mbamain_auser_id FOREIGN KEY (user_id) REFERENCES public.mbamain_auser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mbamain_invite mbamain_invite_project_id_b0c654c8_fk_mbamain_project_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_invite
    ADD CONSTRAINT mbamain_invite_project_id_b0c654c8_fk_mbamain_project_id FOREIGN KEY (project_id) REFERENCES public.mbamain_project(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mbamain_invite mbamain_invite_user_id_b8af2e47_fk_mbamain_auser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_invite
    ADD CONSTRAINT mbamain_invite_user_id_b8af2e47_fk_mbamain_auser_id FOREIGN KEY (user_id) REFERENCES public.mbamain_auser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mbamain_jbs10 mbamain_jbs10_project_id_e914a0cf_fk_mbamain_project_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_jbs10
    ADD CONSTRAINT mbamain_jbs10_project_id_e914a0cf_fk_mbamain_project_id FOREIGN KEY (project_id) REFERENCES public.mbamain_project(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mbamain_jbs5 mbamain_jbs5_project_id_ad16b3e9_fk_mbamain_project_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_jbs5
    ADD CONSTRAINT mbamain_jbs5_project_id_ad16b3e9_fk_mbamain_project_id FOREIGN KEY (project_id) REFERENCES public.mbamain_project(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mbamain_jbs5 mbamain_jbs5_student_signature_id_e08be2f4_fk_mbamain_s; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_jbs5
    ADD CONSTRAINT mbamain_jbs5_student_signature_id_e08be2f4_fk_mbamain_s FOREIGN KEY (student_signature_id) REFERENCES public.mbamain_signature(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mbamain_nominationform mbamain_nominationfo_project_id_f651f7c7_fk_mbamain_p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_nominationform
    ADD CONSTRAINT mbamain_nominationfo_project_id_f651f7c7_fk_mbamain_p FOREIGN KEY (project_id) REFERENCES public.mbamain_project(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mbamain_noticetosubmitform mbamain_noticetosubm_dos_signature_id_7f9a11e9_fk_mbamain_s; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_noticetosubmitform
    ADD CONSTRAINT mbamain_noticetosubm_dos_signature_id_7f9a11e9_fk_mbamain_s FOREIGN KEY (dos_signature_id) REFERENCES public.mbamain_signature(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mbamain_noticetosubmitform mbamain_noticetosubm_hod_signature_id_c0a0ee24_fk_mbamain_s; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_noticetosubmitform
    ADD CONSTRAINT mbamain_noticetosubm_hod_signature_id_c0a0ee24_fk_mbamain_s FOREIGN KEY (hod_signature_id) REFERENCES public.mbamain_signature(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mbamain_noticetosubmitform mbamain_noticetosubm_primary_supervisor_s_aa6e1e30_fk_mbamain_s; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_noticetosubmitform
    ADD CONSTRAINT mbamain_noticetosubm_primary_supervisor_s_aa6e1e30_fk_mbamain_s FOREIGN KEY (primary_supervisor_signature_id) REFERENCES public.mbamain_signature(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mbamain_noticetosubmitform mbamain_noticetosubm_project_id_7f7ac261_fk_mbamain_p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_noticetosubmitform
    ADD CONSTRAINT mbamain_noticetosubm_project_id_7f7ac261_fk_mbamain_p FOREIGN KEY (project_id) REFERENCES public.mbamain_project(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mbamain_noticetosubmitform mbamain_noticetosubm_secondary_supervisor_29656fc5_fk_mbamain_s; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_noticetosubmitform
    ADD CONSTRAINT mbamain_noticetosubm_secondary_supervisor_29656fc5_fk_mbamain_s FOREIGN KEY (secondary_supervisor_signature_id) REFERENCES public.mbamain_signature(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mbamain_noticetosubmitform mbamain_noticetosubm_student_signature_id_47724584_fk_mbamain_s; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_noticetosubmitform
    ADD CONSTRAINT mbamain_noticetosubm_student_signature_id_47724584_fk_mbamain_s FOREIGN KEY (student_signature_id) REFERENCES public.mbamain_signature(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mbamain_passwordresettoken mbamain_passwordresettoken_user_id_e863672b_fk_mbamain_auser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_passwordresettoken
    ADD CONSTRAINT mbamain_passwordresettoken_user_id_e863672b_fk_mbamain_auser_id FOREIGN KEY (user_id) REFERENCES public.mbamain_auser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mbamain_project mbamain_project_student_id_c98e2974_fk_mbamain_auser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_project
    ADD CONSTRAINT mbamain_project_student_id_c98e2974_fk_mbamain_auser_id FOREIGN KEY (student_id) REFERENCES public.mbamain_auser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mbamain_signature mbamain_signature_user_id_9898f271_fk_mbamain_auser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_signature
    ADD CONSTRAINT mbamain_signature_user_id_9898f271_fk_mbamain_auser_id FOREIGN KEY (user_id) REFERENCES public.mbamain_auser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mbamain_studentprofile mbamain_studentprofile_user_id_f8675222_fk_mbamain_auser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_studentprofile
    ADD CONSTRAINT mbamain_studentprofile_user_id_f8675222_fk_mbamain_auser_id FOREIGN KEY (user_id) REFERENCES public.mbamain_auser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mbamain_studentsupervisorform mbamain_studentsuper_project_id_7690e705_fk_mbamain_p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_studentsupervisorform
    ADD CONSTRAINT mbamain_studentsuper_project_id_7690e705_fk_mbamain_p FOREIGN KEY (project_id) REFERENCES public.mbamain_project(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mbamain_supervisorprofile mbamain_supervisorprofile_user_id_961c19d5_fk_mbamain_auser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mbamain_supervisorprofile
    ADD CONSTRAINT mbamain_supervisorprofile_user_id_961c19d5_fk_mbamain_auser_id FOREIGN KEY (user_id) REFERENCES public.mbamain_auser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

