from django.shortcuts import render
from django.urls import path

from .views import auth_views, profile_views, projects_views, supervisor_view, uploads_views, Invite, studentSupervisorForm, JBS5form, NominationForm, JBS10

app_name = "mba_main"
urlpatterns = [
    path("", projects_views.projects, name="index"),
    path("update/module", profile_views.update_module,name="update_module"),
    path("projects", projects_views.projects, name="projects"),
    path("projects/create", projects_views.create_project, name="create_project"),
    path("projects/update/<int:project_id>", projects_views.update_project, name="update_project"),
    path("projects/manage/<str:id>", projects_views.manage_project, name="student_manage_project"),
    path("profile", profile_views.profile, name="profile"),
    path("invites", Invite.invites, name="index_scholar"),
    path("accept/invite/<int:invite_id>", Invite.accept_invite, name="accept_invite"),
    path("decline/invite/<int:invite_id>", Invite.decline_invite, name="decline_invite"),
    path("invites/examiner", Invite.examiner_invites, name="examiner_invites"),
    path("accept/invite/examiner/<int:invite_id>", Invite.examiner_accept_invite, name="examiner_accept_invite"),
    path("decline/invite/examiner/<int:invite_id>", Invite.examiner_decline_invite, name="examiner_decline_invite"),
    path("scholar/projects", projects_views.projects_scholar, name="projects_scholar"),
    path("scholar/profile", profile_views.profile_scholar, name="profile_scholar"),
    path("examiner/profile", profile_views.profile_examiner, name="profile_examiner"),
    path("examiner/profile/update", profile_views.profile_examiner, name="profile_update_examiner"),
    path("student/profile/update", profile_views.update_student_profile, name="update_student_profile"),
    path("scholar/manage/project/<int:id>", projects_views.scholar_manage_project, name="manage_project"),
    path("scholar/signature", uploads_views.upload_signature, name="upload_signature"),
    path("scholar/remove/interest", profile_views.remove_interest, name="remove_research_interest"),
    path("get/interests/scholar", profile_views.get_interests, name="research_interest_search"),
    path("add/interests/scholar", profile_views.add_interest, name="add_research_interest"),
    path("update/profile", profile_views.update_supervisor_profile, name="update_supervisor_profile"),
    path("download/signature", uploads_views.download_signature, name="download_signature"),
    path("upload/cv", uploads_views.upload_cv, name="upload_cv"),
    path("download/cv", uploads_views.download_cv, name="download_cv"),
    path('notice/form/<str:id>',projects_views.notice_to_submit, name='notice_form'),
    path('submit/notice/form', projects_views.submit_notice_form, name='submit_notice_form'),
    path('sign/notice/form/<int:project_id>', projects_views.sign_notice_form, name='sign-notice-form'),
    path('sign/notice/signature/<int:id>', uploads_views.load_signature, name='load_signature'),
    path("studentsuperivor/form/<int:project_id>", studentSupervisorForm.form, name="student_supervisor_form"),
    path("studentsuperivor/form/sign/<int:project_id>", studentSupervisorForm.signform, name="sign_sp_form"),
    path("jbs5/form/<int:project_id>", JBS5form.form, name="jbs5_form"),
    path('submit/jbs5/form', JBS5form.submit_jbs5_form, name='submit_jbs5_form'),
    path('submit/nomination/form', NominationForm.submit_nomination_form, name='submit_nomination_form'),
    path("jbs5/form/sign/<int:project_id>", JBS5form.signform, name="sign_jbs5"),
    path("jbs10/form/<int:project_id>", JBS10.form, name="jbs10_form"),
    path("jbs10/form/sign/<int:project_id>", JBS10.signform, name="sign_jbs10"),
    path("signout", auth_views.signout, name="signout"),
    path("signup", auth_views.signup, name="signup"),
    path("signin", auth_views.signin, name="signin"),
    path("reset/password", auth_views.reset_password, name="reset_password"),
    path("get/reset/password/token", auth_views.get_reset_token, name="get_reset_token"),
    path("appoint/assessor/<int:assessor_id>", 
         supervisor_view.appoint_assessor, name="appoint_assessor"),
    path("nomination/form/<int:project_id>", 
         NominationForm.form, name="nominaton_form"),
    path("nomination/form/sign/<int:project_id>", 
         NominationForm.signform, name="sign_nominaton_form"),
     path("submit/to/hdc", projects_views.submit_to_hdc, name="submit_to_hdc"),
]