# Generated by Django 5.2.3 on 2025-08-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbamain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='department',
            field=models.TextField(blank=True, null=True),
        ),
    ]
