# Generated by Django 5.2.3 on 2025-08-14 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbamain', '0002_supervisorprofile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JBS10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_uj_staff', models.BooleanField(default=False, null=True)),
                ('ethical_clearance_number', models.TextField(blank=True, max_length=50, null=True)),
                ('capstone_project', models.TextField(choices=[('limited', 'Limited scope dissertation'), ('minor', 'Minor dissertation'), ('dissertation', 'Dissertation'), ('thesis', 'Thesis'), ('monograph', 'Monograph'), ('article', 'By article')], max_length=20, null=True)),
                ('proposed_title', models.TextField(null=True)),
                ('is_4ir_research', models.BooleanField(default=False, null=True)),
                ('previous_title', models.TextField(blank=True, null=True)),
                ('supervisor_name', models.TextField(max_length=200, null=True)),
                ('supervisor_staff_number', models.TextField(max_length=20, null=True)),
                ('cosupervisor1_name', models.TextField(blank=True, max_length=200, null=True)),
                ('cosupervisor1_staff_number', models.TextField(blank=True, max_length=20, null=True)),
                ('cosupervisor2_name', models.TextField(blank=True, max_length=200, null=True)),
                ('cosupervisor2_staff_number', models.TextField(blank=True, max_length=20, null=True)),
                ('previous_supervisor', models.TextField(blank=True, max_length=200, null=True)),
                ('previous_cosupervisor', models.TextField(blank=True, max_length=200, null=True)),
                ('internal_assessor', models.TextField(blank=True, max_length=200, null=True)),
                ('external_assessor1_name', models.TextField(blank=True, max_length=200, null=True)),
                ('external_assessor1_affiliation', models.TextField(blank=True, max_length=200, null=True)),
                ('external_assessor1_qualification', models.TextField(blank=True, max_length=200, null=True)),
                ('external_assessor1_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('external_assessor2_name', models.TextField(blank=True, max_length=200, null=True)),
                ('external_assessor2_affiliation', models.TextField(blank=True, max_length=200, null=True)),
                ('external_assessor2_qualification', models.TextField(blank=True, max_length=200, null=True)),
                ('external_assessor2_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('external_assessor3_name', models.TextField(blank=True, max_length=200, null=True)),
                ('external_assessor3_affiliation', models.TextField(blank=True, max_length=200, null=True)),
                ('external_assessor3_qualification', models.TextField(blank=True, max_length=200, null=True)),
                ('external_assessor3_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('previous_internal_assessor', models.TextField(blank=True, max_length=200, null=True)),
                ('previous_external_assessor', models.TextField(blank=True, max_length=200, null=True)),
                ('supervisor_signed', models.TextField(blank=True, max_length=100, null=True)),
                ('supervisor_signed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jbs10_form', to='mbamain.project')),
            ],
        ),
    ]
