# Generated by Django 5.2.3 on 2025-08-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbamain', '0003_jbs10'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assessor_email',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='assessor_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='assessor_surname',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Subtmited to HDC'), (2, 'Approved by Admin'), (3, 'Rejected by Admin')], default=0),
        ),
    ]
