# Generated by Django 5.2.3 on 2025-08-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbamain', '0004_project_assessor_email_project_assessor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='assessor_email',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='assessor_name',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='assessor_surname',
            field=models.TextField(default=' ', null=True),
        ),
    ]
