# Generated by Django 5.2.3 on 2025-08-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbamain', '0005_alter_project_assessor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Subtmited to HDC'), (2, 'Approved by Admin'), (3, 'Rejected by Admin'), (4, 'project has completed')], default=0),
        ),
    ]
