# Generated by Django 5.2.3 on 2025-08-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbamain', '0006_alter_project_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assessor_1_appointed',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='assessor_2_appointed',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
