# Generated by Django 5.2.3 on 2025-08-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbamain', '0007_project_assessor_1_appointed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jbs10',
            name='student_signed',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jbs10',
            name='student_signed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
