# Generated by Django 5.2.3 on 2025-08-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbamain', '0008_jbs10_student_signed_jbs10_student_signed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='examminerprofile',
            name='number_assessed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
