# Generated by Django 5.2.3 on 2025-08-23 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbamain', '0009_examminerprofile_number_assessed'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sdg_goal',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cv', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Subtmited to ADMIN'), (2, 'Approved by HDC'), (3, 'Rejected by  HDC'), (4, 'Approved by ADMIN'), (5, 'Rejected by  ADMIN'), (6, 'project has completed')], default=0),
        ),
    ]
