# Generated by Django 5.2.3 on 2025-08-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbamain', '0010_project_sdg_goal_alter_cv_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assessor_1_approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='assessor_2_approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='assessor_3_approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='hdc_comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='assessor_1_appointed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='assessor_2_appointed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Subtmited to ADMIN'), (2, 'Approved by HDC'), (3, 'Rejected by  HDC'), (4, 'Approved by ADMIN'), (5, 'Rejected by  ADMIN'), (6, 'project has completed'), (7, 'Approved by HDC')], default=0),
        ),
    ]
