# Generated by Django 5.2.3 on 2025-08-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbamain', '0011_project_assessor_1_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='assessor_email',
        ),
        migrations.RemoveField(
            model_name='project',
            name='assessor_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='assessor_surname',
        ),
        migrations.AddField(
            model_name='project',
            name='assessor_1_email',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='assessor_1_name',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='assessor_1_surname',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='assessor_2_email',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='assessor_2_name',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='assessor_2_surname',
            field=models.TextField(default=' ', null=True),
        ),
    ]
