# Generated by Django 5.2.3 on 2025-08-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbamain', '0012_remove_project_assessor_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examminerprofile',
            name='number_assessed',
        ),
        migrations.AddField(
            model_name='examminerprofile',
            name='approved_before',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Subtmited to ADMIN'), (2, 'Approved for HDC by ADMIN'), (3, 'Rejected by  ADMIN'), (4, 'Approved by ADMIN'), (5, 'Rejected by  ADMIN'), (6, 'project has completed'), (7, 'Approved by HDC')], default=0),
        ),
    ]
