# Generated by Django 5.2.3 on 2025-08-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbamain', '0013_remove_examminerprofile_number_assessed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchinterest',
            name='users',
        ),
        migrations.AddField(
            model_name='invite',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auser',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Main Admin'), (1, 'Admin'), (2, 'Scholar'), (3, 'Student'), (4, 'Examiner'), (5, 'Hdc')], default=3),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Subtmited to ADMIN'), (2, 'Approved for HDC by ADMIN'), (3, 'Rejected by  ADMIN'), (4, 'Approved by ADMIN'), (5, 'Rejected by  ADMIN'), (6, 'project has completed'), (7, 'Verified by HDC')], default=0),
        ),
    ]
