# Generated by Django 5.2.3 on 2025-09-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbamain', '0014_remove_researchinterest_users_invite_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title_approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Subtmited to ADMIN'), (2, 'Approved for HDC by ADMIN'), (3, 'Rejected by  ADMIN'), (4, 'Approved by ADMIN'), (5, 'Rejected by  ADMIN'), (6, 'project has completed'), (7, 'Verified by HDC'), (8, 'JBS5 form submitted'), (9, 'JBS5 declined by admin '), (10, 'JBS5 approved by admin'), (11, 'JBS5 declined by HDC '), (12, 'JBS5 approved by HDC'), (13, 'Notice form submitted'), (14, 'Notice form declined by admin '), (15, 'Notice form approved by admin'), (16, 'Notice form declined by HDC '), (17, 'Notice form approved by HDC')], default=0),
        ),
    ]
