# Generated by Django 5.2.3 on 2025-09-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbamain', '0015_project_title_approved_alter_project_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='nomination_form_approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='nomination_form_submitted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
