# Generated by Django 5.2.3 on 2025-09-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbamain', '0016_project_nomination_form_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='nomination_form_hdc_verified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
