# Generated by Django 5.2.3 on 2025-09-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbamain', '0017_project_nomination_form_hdc_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='intent_form_approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='intent_form_hdc_verified',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='intent_form_submitted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
