# Generated by Django 5.2.3 on 2025-09-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbamain', '0018_project_intent_form_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assessor_1_invite_sent',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='assessor_1_responded',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='assessor_1_response',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='assessor_2_invite_sent',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='assessor_2_responded',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='assessor_2_response',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='assessor_3_invite_sent',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='assessor_3_responded',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='assessor_3_response',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
