# Generated by Django 5.2.3 on 2025-09-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbamain', '0019_project_assessor_1_invite_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jbs5',
            name='amended_co_supervisor',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jbs5',
            name='amended_supervisor',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jbs5',
            name='previous_title',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jbs5',
            name='previously_approved_co_supervisor',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jbs5',
            name='previously_approved_supervisor',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jbs5',
            name='proposed_amendment_title',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jbs5',
            name='proposed_co_supervisor',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jbs5',
            name='proposed_supervisor',
            field=models.TextField(null=True),
        ),
    ]
