# Generated by Django 5.2.3 on 2025-09-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbamain', '0020_jbs5_amended_co_supervisor_jbs5_amended_supervisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jbs5',
            name='amended_co_supervisor',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='jbs5',
            name='amended_supervisor',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='jbs5',
            name='previous_title',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='jbs5',
            name='previously_approved_co_supervisor',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='jbs5',
            name='previously_approved_supervisor',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='jbs5',
            name='proposed_amendment_title',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='jbs5',
            name='proposed_co_supervisor',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='jbs5',
            name='proposed_supervisor',
            field=models.TextField(default='', null=True),
        ),
    ]
