# Generated by Django 5.2.3 on 2025-09-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbamain', '0021_alter_jbs5_amended_co_supervisor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jbs10',
            name='previous_cosupervisor',
        ),
        migrations.RemoveField(
            model_name='jbs10',
            name='previous_external_assessor',
        ),
        migrations.RemoveField(
            model_name='jbs10',
            name='previous_internal_assessor',
        ),
        migrations.RemoveField(
            model_name='jbs10',
            name='previous_supervisor',
        ),
        migrations.AddField(
            model_name='jbs10',
            name='external_assessor1_staff_number',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jbs10',
            name='external_assessor2_staff_number',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jbs10',
            name='external_assessor3_staff_number',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jbs10',
            name='previous_assessor_name',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jbs10',
            name='previous_assessor_staff_number',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jbs10',
            name='previous_cosupervisor_name',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jbs10',
            name='previous_cosupervisor_stuff_number',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jbs10',
            name='previous_external_assessor1_affiliation',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jbs10',
            name='previous_external_assessor1_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='jbs10',
            name='previous_external_assessor1_name',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jbs10',
            name='previous_external_assessor1_qualification',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jbs10',
            name='previous_external_assessor1_staff_number',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jbs10',
            name='previous_external_assessor2_affiliation',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jbs10',
            name='previous_external_assessor2_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='jbs10',
            name='previous_external_assessor2_name',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jbs10',
            name='previous_external_assessor2_qualification',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jbs10',
            name='previous_external_assessor2_staff_number',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jbs10',
            name='previous_external_assessor3_affiliation',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jbs10',
            name='previous_external_assessor3_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='jbs10',
            name='previous_external_assessor3_name',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jbs10',
            name='previous_external_assessor3_qualification',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jbs10',
            name='previous_external_assessor3_staff_number',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jbs10',
            name='previous_supervisor_name',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jbs10',
            name='previous_supervisor_staff_number',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jbs10',
            name='cosupervisor1_name',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jbs10',
            name='cosupervisor2_name',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jbs10',
            name='external_assessor1_affiliation',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jbs10',
            name='external_assessor1_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='jbs10',
            name='external_assessor1_name',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jbs10',
            name='external_assessor1_qualification',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jbs10',
            name='external_assessor2_affiliation',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jbs10',
            name='external_assessor2_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='jbs10',
            name='external_assessor2_name',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jbs10',
            name='external_assessor2_qualification',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jbs10',
            name='external_assessor3_affiliation',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jbs10',
            name='external_assessor3_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='jbs10',
            name='external_assessor3_name',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jbs10',
            name='external_assessor3_qualification',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jbs10',
            name='internal_assessor',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
    ]
