# Generated by Django 5.2.3 on 2025-09-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbamain', '0022_remove_jbs10_previous_cosupervisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jbs10',
            name='previous_assessor_qualification',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
    ]
