# Generated by Django 5.2.3 on 2025-09-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbamain', '0023_jbs10_previous_assessor_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominationform',
            name='degree',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nominationform',
            name='qualification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
