# Generated by Django 5.2.3 on 2025-09-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbamain', '0024_nominationform_degree_nominationform_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='invite_type',
            field=models.BooleanField(default=False),
        ),
    ]
