# Generated by Django 5.2.3 on 2025-09-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbamain', '0025_invite_invite_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assessor_1_email_sent',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='assessor_2_email_sent',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
